[tool.poetry]
name = "kyma-companion"
version = "0.1.0"
description = "Kyma Companion is AI Kyma assistant that helps you to manage your Kyma runtime"
authors = [
    "Muhammad Faizan m.faizan@sap.com",
    "Aleksei Chernyshov aleksei.chernyshov@sap.com",
    "Carina Kothe carina.kothe@sap.com",
    "Friedrich Wilken jens.wilken@sap.com",
    "Tibor Kiss tibor.kiss01@sap.com",
    "Marco Bebway marco.bebway@sap.com",
    "Piotr Bochynski piotr.bochynski@sap.com",
    "Mansur Uralov m.uralov@sap.com",
]
readme = "README.md"
packages = [{ include = "src" }]
license = "Apache-2.0"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12.4"
# Add your production dependencies here
fastapi = "^0.111.0"
pytest = "^8.2.2"
langchain-community = "^0.2.6"
hdbcli = "^2.21.26"

[tool.poetry.group.test.dependencies]
pytest = "^8.2.2"
pytest-mock = "^3.14.0"
pytest-asyncio = "^0.23.7"
types-pyyaml = "^6.0.12.20240311"

[tool.poetry.group.dev.dependencies]
ruff = "v0.4.10"
flake8-bugbear = "^24.4.26"
poethepoet = "^0.27.0"
mypy = "^1.10.1"
flake8 = "^7.1.0"
black = "^24.4.2"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra"
pythonpath = [
    "src"
]
testpaths = [
    "tests",
]

[tool.poe.tasks]
lint = "ruff check ."
typecheck = "mypy . --pretty"
format = "black . --check"
codecheck = ["lint", "typecheck", "format"]
format-fix = "black ."
lint-fix = "ruff check . --fix"
test = "pytest tests"
run = "fastapi run src/main.py --port 8000"
run-local = "fastapi dev src/main.py --port 8000"
