---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-backend
  namespace: ai-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-backend
  template:
    metadata:
      labels:
        app: ai-backend
    spec:
      containers:
      - name: ai-backend
        image: example.com/ai-backend:stable
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            memory: "256Mi" # Minimum amount of memory guaranteed
            cpu: "500m" # Equivalent to 0.5 of a CPU
          limits:
            memory: "3Gi" # Maximum amount of memory the container can use
            cpu: "4" # Equivalent to 4 of a CPU
        env:
        - name: AICORE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: ai-core
              key: clientsecret
        - name: AICORE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: ai-core
              key: clientid
        - name: AICORE_AUTH_URL
          valueFrom:
            secretKeyRef:
              name: ai-core
              key: auth_url
        - name: AICORE_SERVICE_URLS
          valueFrom:
            secretKeyRef:
              name: ai-core
              key: base_url
        - name: AICORE_BASE_URL
          valueFrom:
            secretKeyRef:
              name: ai-core
              key: base_url
        - name: AICORE_RESOURCE_GROUP
          valueFrom:
            secretKeyRef:
              name: ai-core
              key: resource_group
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ai-core
              key: hana_db_url
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: ai-core
              key: hana_db_user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ai-core
              key: hana_db_password
        - name: DATABASE_PORT
          valueFrom:
            secretKeyRef:
              name: ai-core
              key: hana_db_port
        - name: DOCS_TABLE_NAME
          value: "kyma_docs"
        - name: REDIS_HOST
          value: "redis-stack.redis.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
        - name: CONFIG_PATH
          value: "/mnt/config/models-config.json"
        envFrom:
          - configMapRef:
              name: ai-backend-config
        volumeMounts:
          - name: models-config
            mountPath: /mnt/config/models-config.json
            subPath: models-config.json
      volumes:
        - name: models-config
          configMap:
            name: ai-backend-config
            items:
              - key: models-config.json
                path: models-config.json

---
apiVersion: v1
kind: Service
metadata:
  name: ai-backend-service
  namespace: ai-core
spec:
  type: NodePort
  selector:
    app: ai-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000
      nodePort: 32000  # You can specify a port in the range 30000-32767
